apiVersion: v1
kind: Service
metadata:
  name: peerprep-users-service
  namespace: default
  labels:
    app: peerprep-users
spec:
  ports:
  - protocol: TCP
    port: 3002
    targetPort: 3002
  selector:
    app: peerprep-users
  type: ClusterIP
