apiVersion: apps/v1
kind: Deployment
metadata:
  name: peerprep-fe
spec:
  selector:
    matchLabels:
      app: peerprep-fe
  template:
    metadata:
      labels:
        app: peerprep-fe
    spec:
      containers:
      - name: peerprep-fe
        image: gcr.io/peerprep-g32/peerprep-fe@sha256:99305800e35ddbbb9e243eeb0bc638d552c58bec9561d5ec15b61fb9caf10793
        ports:
        - containerPort: 3000
# TODO: secrets instead of .env files?
