apiVersion: apps/v1
kind: Deployment
metadata:
  name: peerprep-fe
spec:
  selector:
    matchLabels:
      app: peerprep-fe
  template:
    metadata:
      labels:
        app: peerprep-fe
    spec:
      containers:
      - name: peerprep-fe
        image: gcr.io/peerprep-g32/peerprep-fe@sha256:35ebe92ea2eb206a584d6dd0124f1e3110fcbd4951acaf6fc53b5f9f7d4fb8af
        ports:
        - containerPort: 3000
# TODO: secrets instead of .env files?
