apiVersion: apps/v1
kind: Deployment
metadata:
  name: peerprep-fe
spec:
  selector:
    matchLabels:
      app: peerprep-fe
  template:
    metadata:
      labels:
        app: peerprep-fe
    spec:
      containers:
      - name: peerprep-fe
        image: gcr.io/peerprep-g32/peerprep-fe@sha256:81730cc9b3761d891e9092e0fa5e07730a9270e23b2135c3c3e98c5a8419e8f9
        ports:
        - containerPort: 3000
# TODO: secrets instead of .env files?
