apiVersion: apps/v1
kind: Deployment
metadata:
  name: peerprep-match-api
  namespace: default
  labels:
    app: peerprep-match-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: peerprep-match-api
  template:
    metadata:
      labels:
        app: peerprep-match-api
    spec:
      containers:
      - name: peerprep-match-api
        image: gcr.io/peerprep-g32/peerprep-match-api@sha256:3637e3bb21b4c29db7dbff0fae749e0178b6e391fac1f60a8ccafa3d1d60a7ac
