apiVersion: v1
kind: Service
metadata:
  name: peerprep-match-api-service
  namespace: default
  labels:
    app: peerprep-match-api
spec:
  ports:
  - protocol: TCP
    port: 3003
    targetPort: 3003
  selector:
    app: peerprep-match-api
  type: ClusterIP
