apiVersion: apps/v1
kind: Deployment
metadata:
  name: peerprep-match-worker
  namespace: default
  labels:
    app: peerprep-match-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: peerprep-match-worker
  template:
    metadata:
      labels:
        app: peerprep-match-worker
    spec:
      containers:
      - name: peerprep-match-worker
        image: gcr.io/peerprep-g32/peerprep-match-worker@sha256:aa605d37615f9ba74244f541be263d147bc6bd79d599121769c9dbd00b46a9b0
