apiVersion: v1
kind: Service
metadata:
  name: peerprep-collab-service
  namespace: default
  labels:
    app: peerprep-collab
spec:
  ports:
  - name: 4321-to-4321-tcp
    protocol: TCP
    port: 4321
    targetPort: 4321
  - name: 9000-to-9000-tcp
    protocol: TCP
    port: 9000
    targetPort: 9000
  selector:
    app: peerprep-collab
  type: ClusterIP
