apiVersion: v1
kind: Service
metadata:
  name: peerprep-collab-service
  namespace: default
  labels:
    app: peerprep-collab
spec:
  ports:
  - name: 1234-to-1234-tcp
    protocol: TCP
    port: 1234
    targetPort: 1234
  - name: 9000-to-9000-tcp
    protocol: TCP
    port: 9000
    targetPort: 9000
  selector:
    app: peerprep-collab
  type: ClusterIP
