apiVersion: apps/v1
kind: Deployment
metadata:
  name: peerprep-code
  namespace: default
  labels:
    app: peerprep-code
spec:
  replicas: 1
  selector:
    matchLabels:
      app: peerprep-code
  template:
    metadata:
      labels:
        app: peerprep-code
    spec:
      containers:
      - name: peerprep-code
        image: gcr.io/peerprep-g32/peerprep-code@sha256:0dadf03363fa924c927810dedd42f80302088c5f9cef19ce31d08c7641d1917e
        securityContext:
          privileged: true