apiVersion: v1
kind: Service
metadata:
  name: peerprep-code-service
  namespace: default
  labels:
    app: peerprep-code
spec:
  ports:
  - protocol: TCP
    port: 4321
    targetPort: 4321
  selector:
    app: peerprep-code
  type: ClusterIP
