apiVersion: apps/v1
kind: Deployment
metadata:
  name: peerprep-questions
  namespace: default
  labels:
    app: peerprep-questions
spec:
  replicas: 1
  selector:
    matchLabels:
      app: peerprep-questions
  template:
    metadata:
      labels:
        app: peerprep-questions
    spec:
      containers:
      - name: peerprep-questions
        image: gcr.io/peerprep-g32/peerprep-questions@sha256:d064525b714180cc5bdd732392540177dbf591ed1704ba72636d13397b8956df
