apiVersion: v1
kind: Service
metadata:
  name: peerprep-questions-service
  namespace: default
spec:
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
  selector:
    app: peerprep-questions
  type: ClusterIP
